
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Depricated platform
#vacuum:
#  - platform: xiaomi_miio
#    host: 192.168.1.144
#    token: !secret roborock6s

device_tracker:
  - platform: traccar
    host: !secret traccar_ip
    username: !secret traccar_user
    password: !secret traccar_pass

sensor:
  - platform: template
    sensors:
      corridor_movement:
        value_template: >-
          {% set movement1 =state_attr ("binary_sensor.motion_sensor_158d00016d56c6", "No motion since") | float %}
          {% set movement2 =state_attr ("binary_sensor.motion_sensor_158d0002ead576", "No motion since") | float %}
          {% set movement3 =state_attr ("binary_sensor.motion_sensor_158d0002ec3445", "No motion since") | float %}

          {% if movement1 > 299 and movement2 > 299 and movement3 > 299 %}
          true
          {%- else -%}
          false
          {%- endif %}
      corridor_movement_night:
        value_template: >-
          {% set movement1 =state_attr ("binary_sensor.motion_sensor_158d00016d56c6", "No motion since") | float %}
          {% set movement2 =state_attr ("binary_sensor.motion_sensor_158d0002ead576", "No motion since") | float %}
          {% set movement3 =state_attr ("binary_sensor.motion_sensor_158d0002ec3445", "No motion since") | float %}

          {% if movement1 > 119 and movement2 > 119 and movement3 > 119 %}
          true
          {%- else -%}
          false
          {%- endif %}

discovery:
  enable:
    - dlna_dmr

#media_player:
#  - platform: dlna_dmr
#    name: Radio
#    url: http://192.168.1.29:8080/dd.xml

switch:
  - platform: template
    switches:
      radio:
        friendly_name: Radio
        #value_template: "{{ is_state('media_player.ne_6451_s10_0022614c0060', 'playing') }}"
        value_template: "{{ states('media_player.ne_6451_s10_0022614c0060') in ['idle', 'unknown', 'unavailable', 'paused', 'playing'] }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.ne_6451_s10_0022614c0060
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.ne_6451_s10_0022614c0060
        icon_template: mdi:radio
      hoover:
        friendly_name: Dobby
        value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          data:
            entity_id: vacuum.xiaomi_vacuum_cleaner
        turn_off:
          service: automation.trigger
          data:
            entity_id: automation.dobby_goes_to_sleep
      ps4_switch:
        friendly_name: PlayStation
        #value_template: "{{ is_state('media_player.playstation_4', 'playing') }}"
        value_template: "{{ states('media_player.playstation_4') in ['idle', 'playing'] }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.playstation_4
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.playstation_4
        icon_template: mdi:gamepad
      sony_tv_switch:
        friendly_name: TV
        value_template: "{{ is_state('media_player.sony_bravia_tv', 'on') }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.sony_bravia_tv
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.sony_bravia_tv
        icon_template: mdi:television

light:
  - platform: group
    name: Bedroom lights
    entities:
      - light.bedroom_ceiling_light
      - light.nikos_light
      - light.cindis_light

notify:
  - platform: slack
    name: slack
    api_key: !secret slack_api
    default_channel: '#notify'
    username: Home Assistant
    icon: https://avatars.slack-edge.com/2021-04-23/1988055427350_2a7cb0e36be355723b8c_48.png

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
