
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.144
    token: !secret roborock6s

sensor:
  - platform: template
    sensors:
      corridor_movement:
        value_template: >-
          {% set movement1 =state_attr ("binary_sensor.motion_sensor_158d00016d56c6", "No motion since") | float %}
          {% set movement2 =state_attr ("binary_sensor.motion_sensor_158d0002ead576", "No motion since") | float %}
          {% set movement3 =state_attr ("binary_sensor.motion_sensor_158d0002ec3445", "No motion since") | float %}

          {% if movement1 > 599 and movement2 > 599 and movement3 > 599 %}
          true
          {%- else -%}
          false
          {%- endif %}

discovery:
  enable:
    - dlna_dmr

#media_player:
#  - platform: dlna_dmr
#    name: Radio
#    url: http://192.168.1.29:8080/dd.xml

switch:
  - platform: template
    switches:
      radio:
        friendly_name: Radio
        value_template: "{{ is_state('media_player.ne_6451_s10_0022614c0060_2', 'playing') }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.ne_6451_s10_0022614c0060_2
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.ne_6451_s10_0022614c0060_2
        icon_template: mdi:radio
      hoover:
        friendly_name: Dobby
        value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          data:
            entity_id: vacuum.xiaomi_vacuum_cleaner
        turn_off:
          service: automation.trigger
          data:
            entity_id: automation.dobby_goes_to_sleep
      ps4_switch:
        friendly_name: PlayStation
        value_template: "{{ is_state('media_player.playstation_4', 'playing') }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.playstation_4
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.playstation_4
        icon_template: mdi:gamepad

notify:
  - platform: slack
    name: slack
    api_key: !secret slack_api
    default_channel: '#notify'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
